# [base]
#   laddr = "0.0.0.0:4200"
#   namespace = "0000DEADBEEF0000"

# [block-submitter]
#   gas-limit = 2000000
#   fee-amount = 1
#   denomination = "celes"
#   celestia-grpc-addr = "192.167.10.0:9090"
#   celestia-rest-addr = "192.167.10.0:26657"
#   chain-id = "ephemeral"
#   timeout = 180000000000
#   broadcast-mode = 1
#   keyring-account-name = "dalc"

# [light-client]

# [keyring]
#   backend = "test"
#   path = "/root"

[base]
  laddr = "0.0.0.0:4200"
  namespace = "0102030405060708"

[block-submitter]
  gas-limit = 2000000
  fee-amount = 1
  denomination = "celes"
  celestia-grpc-addr = "192.167.10.2:9090"
  celestia-rest-addr = "192.167.10.2:26657"
  chain-id = "ephemeral"
  timeout = 180000000000
  broadcast-mode = 1
  keyring-account-name = "dalc"

[light-client]

[keyring]
  backend = "test"
  path = "/root"