version: '3'

services:
  bridge0:
    container_name: bridge0
    image: "ghcr.io/celestiaorg/celestia-node:v0.2.0"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--node.store", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.2:26657",
            "--headers.trusted-hash", 
            "54A8B66D2BEF13850D67C8D474E196BD7485FE5A79989E31B17169371B0A9C96"
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge0/nodekey0:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  bridge1:
    container_name: bridge1
    image: "ghcr.io/celestiaorg/celestia-node:v0.2.0"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--node.store", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.3:26657",
            "--headers.trusted-hash", 
            "54A8B66D2BEF13850D67C8D474E196BD7485FE5A79989E31B17169371B0A9C96"
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge1/nodekey1:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  bridge2:
    container_name: bridge2
    image: "ghcr.io/celestiaorg/celestia-node:v0.2.0"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--node.store", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.4:26657",
            "--headers.trusted-hash", 
            "54A8B66D2BEF13850D67C8D474E196BD7485FE5A79989E31B17169371B0A9C96"
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge2/nodekey2:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  bridge3:
    container_name: bridge3
    image: "ghcr.io/celestiaorg/celestia-node:v0.2.0"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--node.store", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.5:26657",
            "--headers.trusted-hash", 
            "54A8B66D2BEF13850D67C8D474E196BD7485FE5A79989E31B17169371B0A9C96",
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge3/nodekey3:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
